name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.10.2

      - name: Build wheels & test
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
           #CIBW_BEFORE_ALL_LINUX: apt-get update && apt-get install -y libpython3-dev libsctp-dev gcc make
           # Build using the latest manylinux2014 release, instead of the cibuildwheel
           # pinned version
           CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
           CIBW_MANYLINUX_I686_IMAGE: quay.io/pypa/manylinux2014_i686:latest
           CIBW_BEFORE_ALL_LINUX: >
             echo "exclude=mirror.es.its.nyu.edu" >> /etc/yum/pluginconf.d/fastestmirror.conf &&
             rm -f /var/cache/yum/timedhosts.txt &&
             yum install -y lksctp-tools-devel
           #for now just a quick test of loopback
           CIBW_TEST_COMMAND: python3 {project}/test_loopback.py
           #skipping PyPy and musllinux builds
           CIBW_SKIP: "pp* *musllinux*"
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
